### ISSUE TITLE
You didnt specify how to use genderPrediction in readme

### ISSUE THREAD

**Issue by abdushsk** [mandalbiswadip/gender_prediction#1]
Readme consists of the instruction on how to use genderPrediction function,
Please update your readme

**Comment by mandalbiswadip** [comment]
Hi,
Thanks for pointing this out. Will fix it quickly.

Thanks,
Biswadip

**Comment by mandalbiswadip** [comment]
Hi,
Please check the repo again.
Thanks,
Biswadip

**Comment by abdushsk** [comment]
It is more clear now
Thanks
Btw really liked your project
